{
  "providers": ["python"],
  "buildCommand": "pip install -r requirements.txt",
  "startCommand": "python manage.py migrate && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT",
  "nixPkgs": [
    "cairo",
    "pango",
    "gdk-pixbuf"
  ]
}
